name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # Важно для правильных прав доступа

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Setup google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          mkdir -p ./app
          echo "$FIREBASE_CONFIG" > ./app/google-services.json
          jq . ./app/google-services.json || (echo "Invalid JSON"; exit 1)

      - name: Build with Gradle
        run: |
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace --info --no-daemon || \
          (./gradlew --stop; exit 1)

      - name: Find APK files
        if: always()
        run: find app/build/outputs -name "*.apk" -ls

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 5
