name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          mkdir -p ./app
          echo "$FIREBASE_SECRET" > ./app/google-services.json
          echo "File created with size:"
          ls -la ./app/google-services.json

      - name: Validate JSON
        run: |
          sudo apt-get install -y jq
          jq empty ./app/google-services.json

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace --info

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-build
          path: app/build/outputs/apk/debug/app-debug.apk
